from django.contrib import admin
from .models import *
admin.site.register(Area)
admin.site.register(BatchDetail)    
admin.site.register(CartItem)
admin.site.register(City)
admin.site.register(Company)
admin.site.register(Complain)
admin.site.register(CustomerOrder)  
admin.site.register(Delivery)
admin.site.register(DeliveryPerson)
admin.site.register(Feedback)
admin.site.register(Image)
admin.site.register(Offer)
admin.site.register(Order)
admin.site.register(OrderDetail)
admin.site.register(OrderReturn)
admin.site.register(OrderReturnDetail)
admin.site.register(Payment)
admin.site.register(Product)
admin.site.register(ProductCategory)
admin.site.register(ProductSubCategory)
admin.site.register(Production)
admin.site.register(Purchase)
admin.site.register(PurchaseDetail)
admin.site.register(PurchaseReturn)
admin.site.register(PurchaseReturnDetail)
admin.site.register(Rating)
admin.site.register(RawMaterial)
admin.site.register(Role)
admin.site.register(State)
admin.site.register(Supplier)
admin.site.register(UserProfile)
admin.site.register(CustomCakeOrder)
# Register your models here.