# Generated by Django 6.0 on 2026-02-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0008_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreturn',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'approved'), ('REJECTED', 'rejected')], default='REQUESTED', max_length=20),
        ),
    ]
