# Generated by Django 6.0 on 2026-02-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0010_product_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_charges',
            new_name='delivery_charge',
        ),
        migrations.AddField(
            model_name='order',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
