# Generated by Django 6.0 on 2026-02-08 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0011_rename_delivery_charges_order_delivery_charge_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_charge',
            new_name='delivery_charges',
        ),
    ]
