# Generated by Django 6.0 on 2026-02-08 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0012_rename_delivery_charge_order_delivery_charges'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_charges',
            new_name='delivery_charge',
        ),
    ]
