# Generated by Django 6.0 on 2026-02-08 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0015_order_coupon_code_order_discount_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount_amount',
        ),
    ]
