# Generated by Django 6.0 on 2026-02-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0019_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_madeof',
            field=models.TextField(blank=True),
        ),
    ]
