# Generated by Django 6.0 on 2026-02-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0020_product_product_madeof'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCakeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(choices=[('round', 'Round'), ('square', 'Square'), ('heart', 'Heart')], max_length=20)),
                ('layers', models.IntegerField()),
                ('cream', models.CharField(max_length=50)),
                ('topping', models.CharField(max_length=50)),
                ('cake_name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('cake_image', models.TextField()),
                ('payment_method', models.CharField(choices=[('cod', 'Cash on Delivery'), ('razorpay', 'Razorpay')], max_length=20)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
