# Generated by Django 6.0 on 2026-02-25 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0022_customcakeorder_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customcakeorder',
            name='order',
        ),
    ]
