# Generated by Django 6.0 on 2026-02-25 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0023_remove_customcakeorder_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcakeorder',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_cakes', to='bakery.order'),
        ),
    ]
