# Generated by Django 6.0 on 2026-03-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0025_productbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customcakeorder',
            name='filling_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
